In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [3]:
df =pd.read_csv("data/multiple_linear_regress_data.csv")


In [4]:
df.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [7]:
import math
median_bedrooms=math.floor(df.bedrooms.median())
median_bedrooms
# foolring the median

3

In [10]:
df.bedrooms=df.bedrooms.fillna(median_bedrooms)
# filling the nan values with the median vlaues

In [12]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [13]:
reg =linear_model.LinearRegression()
reg.fit(df[["area","bedrooms","age"]],df.price)

LinearRegression()

In [14]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [15]:
reg.intercept_

383725.00000000006

In [16]:
reg.predict([[3000,3,40]])

c:\users\ww\appdata\local\programs\python\python39\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([444400.])

In [17]:
383725+137.25*3000-26025*3-6825*40

444400.0

In [18]:
reg.predict([[2500,4,5]])

c:\users\ww\appdata\local\programs\python\python39\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([588625.])

In [ ]:
# Exercise:
'''
In exercise folder (same level as this notebook on github) there is hiring.csv. This file contains hiring statics for a firm such as experience of candidate, his written test score and personal interview score. Based on these 3 factors, HR will decide the salary. Given this data, you need to build a machine learning model for HR department that can help them decide salaries for future candidates. Using this predict salaries for following candidates,

2 yr experience, 9 test score, 6 interview score

12 yr experience, 10 test score, 10 interview score
'''
'''
To use the python word2number
pip install word2number
'''